# Generated by Django 4.2 on 2024-12-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_taskassign_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('place', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=15)),
                ('call_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10)),
                ('call_outcome', models.CharField(choices=[('rejected', 'Rejected'), ('missed', 'Missed'), ('completed', 'Completed')], max_length=10)),
                ('call_date', models.DateTimeField()),
                ('call_duration', models.DurationField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
