# Generated by Django 4.2 on 2024-12-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('team_leader', 'Team Leader'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
